projects:
  testaws:
    schemaPath: src/graphql/schema.json
    includes:
      - dataOperation
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
